title: CSE Bordeaux
logo: /assets/images/INGELIANCE-2020-COULEURS.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github: [metadata]


sidebar:
  - name: Le bureau et le rôle du CSE
    link: ./bureau.html
  - name: L'offre
    link: ./avantages.html
  - name: La ludothèque
    link: ./ludo.html
  - name: L'utilisation du budget
    link: ./budget.html
